name: Deploy to Neocities

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Publicar en Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_KEY }}
          username: ${{ secrets.NEOCITIES_USERNAME }}
          cleanup: false
          dist_dir: .